config/routes.rb
Rails.application.routes.draw do
  get 'main_page/show'


  get 'main_page/home', to: 'main_page#home'
  post 'main_page/home', to: 'main_page#home'
    post 'main_page/show', to: 'main_page#show'
root 'main_page#home'
resources :locations

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/download.rb
class Download < ApplicationRecord
  geocoded_by :ip
  after_validation :geocode
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address       # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

def mainPage
  render html: "Hlavní stránka testu"
end


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(allowed_params)
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(allowed_params)
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_url, :notice => "Successfully destroyed location."
  end

  private

  def allowed_params
    params.require(:location).permit(:id, :address, :latitude, :longitude)
  end
end

app/controllers/main_page_controller.rb
require "nokogiri" 
require "open-uri"


class MainPageController < ApplicationController
  def home
  end
  
  def show
    @varMail = params[:mail]
    @varUrl = params[:url]
    @varTitle = " "
   #Nokogiri::HTML.parse(open(@varUrl)).title 
   if @varMail.include? "@" 
       if  @varMail.include? "."
       else
       @varMail = "neplatný email"
       end
   else
     @varMail = "neplatný email"
   end
  
  
  
    if @varUrl.include?  "https://"
      @varTitle = Nokogiri::HTML.parse(open(@varUrl)).title
    else
      @varUrl = "neplatná url"
      @varTitle = "neplatná url"
    end
  
  @varIP= request.remote_ip[@varUrl]
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>
<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", location %></td>
      <td><%= link_to "Edit", edit_location_path(location) %></td>
      <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<%= render 'form' %>
<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/main_page/home.html.erb
<div id="table" style="text-align:center">

<h1>Final test</h1>
<p>Zadej URL stránky: </p>


<% #Nokogiri::HTML.parse(open('https://bubenicek-final.herokuapp.com')).title %>

<%= form_tag("main_page/show", method: "post") do %>
  <%= label_tag :url %><br>
  <%= text_field_tag @var = :url %>
  <br>
  <br>
  <%= label_tag :mail %><br>
   <p>E-mail zadávejte ve správném tvaru: <strong>example@email.com</strong></p>
  <%= text_field_tag :mail %>
  <p>
    <%= submit_tag("Submit") %>
  </p>
<% end %>


<p><a hfer="https://medium.com/ruby-on-rails-development/geocoder-gem-34e15ee95086">GeoCoder</a></p>
<p><a hfer="https://medium.com/@ericschwartz7/rails-mailer-tutorial-82700f6737d9">Mail</a></p>





    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>


</div>

app/views/main_page/show.html.erb
<style>
  html {
  height: 98%;
}

body {
  color: white;
  height: 98%;
}

#table {

  margin-left: 10%;
  background-color: #252525;
  height: 98%;
  width: 80%;
  border: 3px;
  border-style: double;
  border-color: red;
  text-align: center;
}
#text {
  width: 50%
  margin: 0 auto;
  text-align: justify;
  color:yellow;
}
  #nadpis {
    text-decoration: underline;
    text-decoration-color: red;
    color:white;
  }
  

#vysledek {
  text-align: left;
  margin-left: 2px;
}

a {
  font-size: 14pt;
  font-weight: bold;
  text-decoration: none;
  color:white;
}

#odkaz{
  text-decoration:none;
  color:yellow;
}

  
</style>

<div id="table">
<div id="text">
<h1 id="nadpis">Výsledek hledání</h1>
<p></p>

<p> <a>URL:</a>  <a href = "<%=  @varUrl %>" id ="odkaz"><%=  @varUrl %></a></p>
<p><a>Title:</a> <%= @varTitle %></p>
<p><a>Mail:</a> <%= @varMail%></p>
<p><a>IP:</a> <%= @varIP%></p>
</div>
</div>